name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Git checkout repository
        uses: actions/checkout@v3
      - name: Run Test
        run: make test
  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout repository
        uses: actions/checkout@v3
      - name: Generate coverage report
        uses: ncruces/go-coverage-report@v0.1.9
